# Generated by Django 4.0.2 on 2022-04-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='amount',
        ),
    ]
